module

/-
Uniformizer input for the Stickelberger step of the Catalan formalization.

Goal: in the cyclotomic field `K = ℚ(ζ_n)` of conductor `n = ell * (ell ^ f - 1)`, for a prime
ideal `P` of `𝓞 K` above `ell`, a primitive `ell`-th root of unity `z` satisfies
`z - 1 ∈ P` and `z - 1 ∉ P ^ 2`, i.e. `z - 1` is a uniformizer at `P`.

Proof outline:
* `IsCyclotomicExtension.Rat.ramificationIdx_eq` with `k = 0`, `m = ell ^ f - 1` gives
  `ramificationIdx P ℤ = ell - 1`;
* `IsDedekindDomain.ramificationIdx_eq_multiplicity` turns this into
  `multiplicity P (span {(ell : 𝓞 K)}) = ell - 1`;
* `IsCyclotomicExtension.Rat.associated_zeta_sub_one_pow_prime` gives
  `Associated ((z - 1) ^ (ell - 1)) (ell : 𝓞 K)`.
Membership then follows from primality of `P`, and non-membership in `P ^ 2` from
`ell ≤ 2 * (ell - 1)` together with the multiplicity computation.
-/
public import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
public import Mathlib.RingTheory.RamificationInertia.Ramification

/-!
# `Catalan.Stickelberger.Uniformizer`

Part of the Catalan formalization.
-/

@[expose] public section

set_option linter.unusedSectionVars false

namespace Catalan.Stickelberger

open Ideal NumberField

/-- If `ell` is prime with `2 < ell`, `0 < f` and `m = ell ^ f - 1`, then `ell ∤ m`. -/
theorem not_dvd_of_eq_pow_sub_one {ell f m : ℕ} (hell : 2 < ell) (hf : 0 < f)
    (hm : m = ell ^ f - 1) : ¬ ell ∣ m := by
  intro h
  have hpow : 1 ≤ ell ^ f := Nat.one_le_pow _ _ (by omega)
  have hdvd : ell ∣ ell ^ f := dvd_pow_self ell (by omega)
  have h1 : ell ∣ ell ^ f - (ell ^ f - 1) := Nat.dvd_sub hdvd (hm ▸ h)
  rw [show ell ^ f - (ell ^ f - 1) = 1 by omega] at h1
  have := Nat.le_of_dvd one_pos h1
  omega

section Main

variable (ell : ℕ) [Fact ell.Prime] (K : Type*) [Field K] [NumberField K]

/-- The image in `𝓞 K` of the ideal of `ℤ` generated by `ell`. -/
theorem map_span_intCast_eq :
    (span {(ell : ℤ)}).map (algebraMap ℤ (𝓞 K)) = span {(ell : 𝓞 K)} := by
  rw [Ideal.map_span]
  simp

theorem span_natCast_ne_bot : (span {(ell : 𝓞 K)}) ≠ ⊥ := by
  rw [Ne, Ideal.span_singleton_eq_bot]
  simpa using (Fact.out : Nat.Prime ell).ne_zero

variable (P : Ideal (𝓞 K)) [P.IsPrime] [P.LiesOver (span {(ell : ℤ)})]

theorem natCast_mem_of_liesOver : (ell : 𝓞 K) ∈ P := by
  have h := P.over_def (span {(ell : ℤ)})
  have h2 : (ell : ℤ) ∈ Ideal.under ℤ P := by
    rw [← h]; exact Ideal.mem_span_singleton_self _
  simpa using h2

theorem span_natCast_le_of_liesOver : (span {(ell : 𝓞 K)}) ≤ P := by
  rw [Ideal.span_singleton_le_iff_mem]
  exact natCast_mem_of_liesOver ell K P

/-- `P` occurs with finite multiplicity in `span {(ell : 𝓞 K)}`. -/
theorem finiteMultiplicity_span_natCast :
    FiniteMultiplicity P (span {(ell : 𝓞 K)}) := by
  classical
  have hPbot : P ≠ ⊥ :=
    ne_bot_of_le_ne_bot (span_natCast_ne_bot ell K) (span_natCast_le_of_liesOver ell K P)
  exact finiteMultiplicity_of_emultiplicity_eq_natCast
    (UniqueFactorizationMonoid.emultiplicity_eq_count_normalizedFactors
      (Ideal.prime_of_isPrime hPbot inferInstance).irreducible
      (span_natCast_ne_bot ell K))

end Main

/-- `ell` 在 `P` 处的重数恰为 `ell - 1`（即 `P` 在 `ell` 上方的分歧指数）。

这个重数公式用于互补配对和理想分解。 -/
theorem multiplicity_span_natCast_eq (ell f m n : ℕ) [Fact ell.Prime]
    (K : Type*) [Field K] [NumberField K]
    (P : Ideal (NumberField.RingOfIntegers K)) [P.IsPrime]
    [P.LiesOver (Ideal.span {(ell : ℤ)})]
    [IsCyclotomicExtension {n} ℚ K]
    (hell : 2 < ell) (hf : 0 < f) (hm : m = ell ^ f - 1) (hn : n = ell * m) :
    multiplicity P (Ideal.span {(ell : 𝓞 K)}) = ell - 1 := by
  have hmdvd : ¬ ell ∣ m := not_dvd_of_eq_pow_sub_one hell hf hm
  have hram : P.ramificationIdx ℤ = ell - 1 := by
    have h := IsCyclotomicExtension.Rat.ramificationIdx_eq (p := ell) (k := 0) (m := m) n K P
      (by rw [hn, pow_one]) hmdvd
    simpa using h
  rw [← map_span_intCast_eq ell K,
    ← IsDedekindDomain.ramificationIdx_eq_multiplicity (Ideal.span {(ell : ℤ)}) P
      (by rw [map_span_intCast_eq]; exact span_natCast_ne_bot ell K), hram]

/-- 上一条的 `emultiplicity` 版本。 -/
theorem emultiplicity_span_natCast_eq (ell f m n : ℕ) [Fact ell.Prime]
    (K : Type*) [Field K] [NumberField K]
    (P : Ideal (NumberField.RingOfIntegers K)) [P.IsPrime]
    [P.LiesOver (Ideal.span {(ell : ℤ)})]
    [IsCyclotomicExtension {n} ℚ K]
    (hell : 2 < ell) (hf : 0 < f) (hm : m = ell ^ f - 1) (hn : n = ell * m) :
    emultiplicity P (Ideal.span {(ell : 𝓞 K)}) = ((ell - 1 : ℕ) : ℕ∞) := by
  rw [(finiteMultiplicity_span_natCast ell K P).emultiplicity_eq_multiplicity,
    multiplicity_span_natCast_eq ell f m n K P hell hf hm hn]

/-- `z - 1` is a uniformizer at any prime `P` of `𝓞 K` above `ell`, where `K` is the cyclotomic
field of conductor `n = ell * (ell ^ f - 1)` and `z` is a primitive `ell`-th root of unity. -/
theorem zeta_sub_one_mem_not_mem_sq (ell f m n : ℕ) [Fact ell.Prime]
    (K : Type*) [Field K] [NumberField K]
    (P : Ideal (NumberField.RingOfIntegers K)) [P.IsPrime]
    [P.LiesOver (Ideal.span {(ell : ℤ)})]
    [IsCyclotomicExtension {n} ℚ K]
    (hell : 2 < ell) (hf : 0 < f) (hm : m = ell ^ f - 1) (hn : n = ell * m)
    {z : K} (hz : IsPrimitiveRoot z ell) :
    hz.toInteger - 1 ∈ P ∧ hz.toInteger - 1 ∉ P ^ 2 := by
  -- `multiplicity P (ell) = ell - 1`，分歧指数已提成独立定理
  have hmul : multiplicity P (Ideal.span {(ell : 𝓞 K)}) = ell - 1 :=
    multiplicity_span_natCast_eq ell f m n K P hell hf hm hn
  have hfin : FiniteMultiplicity P (Ideal.span {(ell : 𝓞 K)}) :=
    finiteMultiplicity_span_natCast ell K P
  have hellP : (ell : 𝓞 K) ∈ P := natCast_mem_of_liesOver ell K P
  -- `(z - 1) ^ (ell - 1)` is associated to `ell`
  have hassoc : Associated ((hz.toInteger - 1) ^ (ell - 1)) (ell : 𝓞 K) :=
    IsCyclotomicExtension.Rat.associated_zeta_sub_one_pow_prime ell hz
  refine ⟨?_, ?_⟩
  · -- `(z - 1) ^ (ell - 1) ∈ P`, hence `z - 1 ∈ P` since `P` is prime
    have hpow : (hz.toInteger - 1) ^ (ell - 1) ∈ P := by
      obtain ⟨c, hc⟩ := hassoc.symm.dvd
      rw [hc]
      exact Ideal.mul_mem_right _ _ hellP
    exact (‹P.IsPrime›).mem_of_pow_mem _ hpow
  · intro hmem
    -- if `z - 1 ∈ P ^ 2` then `ell ∈ P ^ (2 * (ell - 1)) ≤ P ^ ell`, contradicting
    -- `multiplicity P (ell) = ell - 1 < ell`
    have h1 : (hz.toInteger - 1) ^ (ell - 1) ∈ P ^ (2 * (ell - 1)) := by
      rw [pow_mul]
      exact Ideal.pow_mem_pow hmem _
    have h2 : (ell : 𝓞 K) ∈ P ^ (2 * (ell - 1)) := by
      obtain ⟨c, hc⟩ := hassoc.dvd
      rw [hc]
      exact Ideal.mul_mem_right _ _ h1
    have h3 : (ell : 𝓞 K) ∈ P ^ ell :=
      Ideal.pow_le_pow_right (by omega) h2
    have h4 : P ^ ell ∣ Ideal.span {(ell : 𝓞 K)} := by
      rw [Ideal.dvd_iff_le, Ideal.span_singleton_le_iff_mem]
      exact h3
    exact (hfin.multiplicity_lt_iff_not_dvd.mp (by omega)) h4

end Catalan.Stickelberger
