module

/-
Witt vector tower over a finite residue field.

Deliverable for the Catalan / Mihăilescu formalization: a concrete henselian
local ring with prescribed finite residue field, namely the ring of Witt
vectors `WittVector ell F`.

Self-contained: imports only Mathlib.
-/
public import Mathlib.RingTheory.WittVector.DiscreteValuationRing
public import Mathlib.RingTheory.WittVector.Complete
public import Mathlib.RingTheory.Henselian
public import Mathlib.RingTheory.DedekindDomain.Basic
public import Mathlib.FieldTheory.Perfect

/-!
# `Catalan.Stickelberger.WittTower`

Part of the Catalan formalization.
-/

@[expose] public section

noncomputable section

namespace Catalan.Stickelberger

open WittVector

/-! ### Instances available for `WittVector ell F` with `F` finite of characteristic `ell`

`F` finite + reduced gives `PerfectRing F ell`
(`PerfectRing.ofFiniteOfIsReduced`), which unlocks both
`WittVector.isDiscreteValuationRing` and `WittVector.isAdicCompleteIdealSpanP`.
-/

section

variable (ell : ℕ) [hp : Fact ell.Prime]
variable (F : Type*) [Field F] [Fintype F] [CharP F ell]

/-- The maximal ideal of `WittVector ell F` is the kernel of the constant-coefficient map,
i.e. the ideal generated by `ell`. -/
theorem wittVector_span_eq_maximalIdeal :
    Ideal.span {(ell : WittVector ell F)} = IsLocalRing.maximalIdeal (WittVector ell F) := by
  rw [← WittVector.ker_constantCoeff]
  exact IsLocalRing.ker_eq_maximalIdeal
    (WittVector.constantCoeff : WittVector ell F →+* F) (WittVector.constantCoeff_surjective ell)

end

/-- The Witt vector ring over a finite field is a henselian local ring. -/
theorem wittVector_henselianLocalRing (ell : ℕ) [hp : Fact ell.Prime]
    (F : Type*) [Field F] [Fintype F] [CharP F ell] :
    HenselianLocalRing (WittVector ell F) := by
  have hmax := wittVector_span_eq_maximalIdeal ell F
  refine { __ := (inferInstance : IsLocalRing (WittVector ell F)), is_henselian := ?_ }
  intro f hf a₀ h₁ h₂
  obtain ⟨a, ha₁, ha₂⟩ :=
    HenselianRing.is_henselian (I := Ideal.span {(ell : WittVector ell F)}) f hf a₀
      (by rw [hmax]; exact h₁) (h₂.map _)
  exact ⟨a, ha₁, by rwa [← hmax]⟩

/-- It is also a Dedekind domain, through the discrete valuation ring instance. -/
theorem wittVector_isDedekindDomain (ell : ℕ) [hp : Fact ell.Prime]
    (F : Type*) [Field F] [Fintype F] [CharP F ell] :
    IsDedekindDomain (WittVector ell F) :=
  inferInstance

/-- The residue map is a surjective ring homomorphism with kernel the maximal ideal. -/
theorem wittVector_residue_hom (ell : ℕ) [hp : Fact ell.Prime]
    (F : Type*) [Field F] [Fintype F] [CharP F ell] :
    ∃ π : WittVector ell F →+* F, Function.Surjective π ∧
      ∀ a : WittVector ell F, π a = 0 ↔ a ∈ IsLocalRing.maximalIdeal (WittVector ell F) := by
  refine ⟨WittVector.constantCoeff, WittVector.constantCoeff_surjective ell, fun a => ?_⟩
  rw [← RingHom.mem_ker, WittVector.ker_constantCoeff, wittVector_span_eq_maximalIdeal ell F]

/-- The residue map of `wittVector_residue_hom` is the 0th ghost component. -/
theorem wittVector_constantCoeff_eq_ghostComponent_zero (ell : ℕ) [hp : Fact ell.Prime]
    (F : Type*) [Field F] [Fintype F] [CharP F ell] (a : WittVector ell F) :
    (WittVector.constantCoeff a : F) = WittVector.ghostComponent 0 a := by
  simp [WittVector.ghostComponent_apply, wittPolynomial_zero]

end Catalan.Stickelberger
