module

public import Mathlib

/-! Shared cyclotomic definitions used in the Catalan proof.
The explicit `p` parameter in `G` and `R` is retained in their signatures. -/

/-!
# `Catalan.Cyclotomic.Basic`

Part of the Catalan formalization.
-/

@[expose] public section

open scoped BigOperators nonZeroDivisors Pointwise
open NumberField

noncomputable section
namespace Catalan

/-- Interface: the Galois group of K/Q; p is an explicit phantom parameter. -/
abbrev G (p : ℕ) (K : Type*) [Field K] [NumberField K] := K ≃ₐ[ℚ] K
/-- Interface: the integral group ring Z[G]. -/
abbrev R (p : ℕ) (K : Type*) [Field K] [NumberField K] := MonoidAlgebra ℤ (G p K)

section CyclotomicPrelude
variable (p : ℕ) [hp : Fact p.Prime]
variable (K : Type*) [Field K] [NumberField K]
  [hcycl : IsCyclotomicExtension {p} ℚ K]

/-- The fixed primitive p-th root used throughout the shared interface. -/
noncomputable def ζ : K := IsCyclotomicExtension.zeta p ℚ K

lemma ζ_spec : IsPrimitiveRoot (ζ p K) p :=
  IsCyclotomicExtension.zeta_spec p ℚ K

/-- Interface: sigma_a sends a p-th root of unity to its a-th power. -/
noncomputable def σ (a : (ZMod p)ˣ) : G p K := by
  letI : NeZero p := ⟨hp.out.ne_zero⟩
  exact (IsCyclotomicExtension.Rat.galEquivZMod p K).symm a

lemma σ_apply_ζ (a : (ZMod p)ˣ) :
    σ p K a (ζ p K) = ζ p K ^ (a : ZMod p).val := by
  letI : NeZero p := ⟨hp.out.ne_zero⟩
  simpa only [σ, MulEquiv.apply_symm_apply] using
    IsCyclotomicExtension.Rat.galEquivZMod_apply_of_pow_eq p K
      ((IsCyclotomicExtension.Rat.galEquivZMod p K).symm a) (ζ_spec p K).pow_eq_one

lemma σ_mul (a b : (ZMod p)ˣ) : σ p K (a * b) = σ p K a * σ p K b := by
  letI : NeZero p := ⟨hp.out.ne_zero⟩
  exact (IsCyclotomicExtension.Rat.galEquivZMod p K).symm.map_mul a b

lemma σ_bijective : Function.Bijective (σ p K) := by
  letI : NeZero p := ⟨hp.out.ne_zero⟩
  exact (IsCyclotomicExtension.Rat.galEquivZMod p K).symm.bijective

/-- The automorphism corresponding to minus one modulo p. -/
noncomputable def ι : G p K := σ p K (-1)

/-- Interface: Theta_k = sum_a floor(a*k/p) sigma_a^(-1). -/
noncomputable def ΘS (k : ℕ) : R p K :=
  ∑ a : (ZMod p)ˣ, MonoidAlgebra.single (σ p K a)⁻¹
    ((((a : ZMod p).val * k : ℕ) / p : ℕ) : ℤ)

/-- Interface: p*theta = sum_a a sigma_a^(-1). -/
noncomputable def pθ : R p K :=
  ∑ a : (ZMod p)ˣ, MonoidAlgebra.single (σ p K a)⁻¹
    (((a : ZMod p).val : ℕ) : ℤ)

/-- The `ℤ`-span generated by all natural-index values and `pθ`. -/
def stickSpan : Submodule ℤ (R p K) :=
  Submodule.span ℤ (Set.range (ΘS p K) ∪ {pθ p K})
end CyclotomicPrelude

end Catalan
